### ISSUE TITLE
why do you use Splunk

### ISSUE THREAD

**Issue by fizz12344321** [Bre77/BAD_TA_metricperfmon#1]
Hi, i am reading your repository and i love it, but i have a question, why do you use Splunk ? Can u tell me your purpose, the pros and cons of Splunk, why don't u use Micrometer, Prometheus, grafana. Thank u so much

**Comment by Bre77** [comment]
Splunk handles the entire stack of machine data for Enterprises. From collection, transfer, parsing, storage, archive, search, reporting, alerting, visualisation, IT Ops, Security Ops, and everything developers like me can create on top of it.

I also use Splunk because it's the tool my employers, my teams, and now my customers use.
